INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('Kim wipes','lab supplies',10,99);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('gloves', 'lab supplies'20,99);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('lab coats','lab supplies',4,99);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('treats','food supplies',35,99);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('pens','office supplies',5,99);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('coffee','food supplies',20,99);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('sticky notes','office supplies',2,99);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('shoe covers','lab supplies',3,99);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('face mask','lab supplies',4,99);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('paper towels','housewares',7,99);
